### ISSUE TITLE
DIAGNOSTICS section: issue with MPD estimates in Tables 15-19 (eg, hg.parameter.est.table)

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#10]
Rob's keen eye spied an inconsistency between the plotted MPD values which are near equal to the median posterior values, and the table MPD values. The plotted values (Figures 18-22, eg, make.priors.posts.plot) appear correct, and what seems to be happening in Tables 15-19 (eg, hg.parameter.est.table) is a duplication of MPD values in rows 7 and 8. I looked and confirmed this error was in the 2017 assessment too. Check your PCod...

**Comment by cgrandin** [comment]
I'll look at this

**Comment by cgrandin** [comment]
Fixed it. Will check PCod assessment
