### ISSUE TITLE
Table needed for 2017/18 catch

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#11]
See sentence in the SR:

"Combined commercial removals from 2010 to 2018 from the roe, food and bait, and special use
fisheries are presented for the major stocks in Table x."

combining catches acoss gears will eliminate any third party concerns.

**Comment by jaclyncleary** [comment]
please also add SOK in lbs for CC and PRD
Sorry to keep going around and around on this.

**Comment by grinnellm** [comment]
I think there may be some privacy issues with SOK -- are we OK including these in the SR?

**Comment by grinnellm** [comment]
I have added the tables, just waiting to check about privacy issues before I close this.

**Comment by grinnellm** [comment]
That was a question for you: PRD has privacy issues (only in 2016 I think) -- are we OK including these data in the SR, or should I omit that year?

**Comment by jaclyncleary** [comment]
combining catches across the three gears (roe GN+roe SN+FB+SU)-  will eliminate any third party concerns.

**Comment by grinnellm** [comment]
But for SOK.. PRD in 2016 has an issue.

**Comment by grinnellm** [comment]
Reminder for me: WP for PRD harvest in 2016.
