### ISSUE TITLE
New HCR outputs

### ISSUE THREAD

**Issue by cgrandin** [grinnellm/HerringAssess#12]
@jaclyncleary Where are the new HCR outputs supposed to go? In a table?

**Comment by jaclyncleary** [comment]
Good question.
Putting in a simple table with two columns- HCR description and TAC is good starting point.
From here I can decide if it'll be table or text. 
thanks!

**Comment by cgrandin** [comment]
There is no table yet, but the values have been calculated. They can be found at the end of custom-knitr-variables.R and are:

*hcr.sog*
*wcvi.sog*

They look like this:
*hcr.sog*
minE_rel50_hr10_cap2            minHS3060_hr20       minHS3060_hr10_cap2 minE_rel50_hr10_cap2_slow 
                   2.0000                   25.7908                    2.0000                    0.0000 
      minHS3060_hr20_slow  minHS3060_hr10_cap2_slow 
                  25.7908                    2.0000 

*hcr.wcvi*
minE_rel50_hr10_cap2            minHS3060_hr20       minHS3060_hr10_cap2 minE_rel50_hr10_cap2_slow 
                 2.000000                  3.792668                  1.896334                  0.000000 
      minHS3060_hr20_slow  minHS3060_hr10_cap2_slow 
                 3.792668                  1.896334

**Comment by grinnellm** [comment]
Thanks Chris, this is great. We get 25.8 t for SoG and 0.7 t for WCVI.

**Comment by grinnellm** [comment]
Thanks Chris, this is great!

**Comment by cgrandin** [comment]
Ok, glad it is working
!

**Comment by jaclyncleary** [comment]
it's perfect, thank you!
