### ISSUE TITLE
inconsistencies between P< 0.3SB0 in decision tables (prd.decision.table) and reference point tables (prd.ref.points.table)

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#13]
values reflecting P < 0.30SB0 are not consistent between stock.decision.table and stock.ref.points.table (for all stocks) for 2019. 

My suspicion is the wrong SB0 value is being used in the new tables. We spent a long time last year making sure the decision tables were calculating correctly so I'm 99.9% sure the values in cell 1 of these tables are correct.

I expect 2018 we'll see the same with 2018 values in stock.ref.points.table are also incorrect but I don't have a point of comparison...

**Comment by cgrandin** [comment]
Ahh yes I see the problem

**Comment by cgrandin** [comment]
I think the P<0.3B0 should not be in the reference point table. It doen't really make sense to be in there..

**Comment by jaclyncleary** [comment]
well we're only including the decision tables for CC and PRD stocks.
Could we put the P<0.30SBo for each stock in a new separate table?

**Comment by cgrandin** [comment]
I didn't realize that, so I suppose they are ok where they are. I just have to fix the issue=

**Comment by cgrandin** [comment]
There's no 2018 in the projection file so the numbers and probabilities will be based on the output from the base model..

**Comment by jaclyncleary** [comment]
hmm, right. what then do you use to calculate p<0.3sbo in 2018?

**Comment by cgrandin** [comment]
The sbt1_2018 column in iscam_sbt_mcmc.csv

**Comment by jaclyncleary** [comment]
p<0.3sbo in 2018 using base model is correct.

**Comment by cgrandin** [comment]
Done in commit 6d0e703c582ff0b9681c21ee1b551e5dddea5722
