### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by cgrandin** [grinnellm/HerringAssess#23]
\textsuperscript{\ref{fnDFO2016}}

in 3_analysis.rnw, line 589

**Comment by grinnellm** [comment]
I've fixed this and committed. Let me know if it's still broken. It's a reference to the first footnote, which I accidentally had as `fnDFO2016` the first time. Yesterday I corrected the year to 2018, so this is `fnDFO2018` now. Sorry for the mix up.

**Comment by cgrandin** [comment]
It's all good :+1:
