### ISSUE TITLE
Alternative text for figures generated on the fly in `knitr`

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/HerringAssess#40]
I'm using Andy's fix to get "alternative text" for figures to comply with CSAP Web Accessibility requirements, as suggested [here](https://github.com/pbs-assess/csas-style/issues/3). This works for Figure 1 (map of BC), which is loaded via `includegraphics` like so:

`\pdftooltip{\includegraphics[width=\linewidth]{\Sexpr{file.path(rootd.static.figs, "BC.png")}}}{Figure~\ref{figBC}}`

However, this doesn't seem to work when graphics are generated in R code chunks `<<>>@` as in Figure 2 (major catch):

`\pdftooltip{
<<catch.major, fig.width=figWidth, fig.height=ceiling(length(allRegions$major)/2)*2+0.5>>=
PlotCatch(SARs = allRegions$major,
          dat = catch)
@
}{Figure~\ref{figCatchMajor}}`

These two examples are in `8_figures.rnw`. Any idea how to do this, other than reverting to how I originally made these figures (i.e., make them via `Models.R`, save the *.png, and the use `includegraphcs`)?

**Comment by grinnellm** [comment]
PS You will have to pull `csas-style-sr` to compile the PDF.

**Comment by cgrandin** [comment]
Hi Matt, I have built the doc and did the "Read out loud" function in Adobe acrobat and both these figure captions are read correctly. I'm not sure what you're trying to accomplish. I have time right though so let me know.

**Comment by grinnellm** [comment]
Seems silly I know, but the 'read out loud' should say "Figure 2" when it gets to Figure 2, and then read the caption which starts "Figure 2. Time series..."
It does this for Figure 1: if you read the page it says "Pacific Region. Science Response: Pacific Herring. Figures. **Figure 1.** Figure 1. Boundaries for..."
CSAS requires an "alternative text" for the figure itself, which consists of "Figure x".

**Comment by cgrandin** [comment]
Actually mine doesn't, it just says Figure 1 once
Why would you want it to say it twice?

**Comment by grinnellm** [comment]
Great question!
Really? If you hover your mouse over Figure 1 do you get a tool tip that says "Figure 1"? It should -- that's what the 'pdftooltip{}` command does in "8_figures.rnw" (line 6).

**Comment by cgrandin** [comment]
Yes I do, but it doesn't read that out loud. Ok, it makes sense, they want a tooltip for each figure right?

**Comment by grinnellm** [comment]
Funny, mine gets read out loud.
Well, what they actually want is "Alternate text" (for Accessibility) for each figure, and we're hoping that the tooltip will work. I believe Andy recently had some success with this?

**Comment by cgrandin** [comment]
OK, it's coming back. I talked to him and he had it working the same way you did, for includegraphics only, not knitr chunks.

**Comment by grinnellm** [comment]
OK, thanks. You're not aware of how to get tooltips for knitr chunks? If so, I may revert to using `\includegraphics{}`.

**Comment by cgrandin** [comment]
If this were in RMarkdown we could inject latex code to fix this in but without it, I don't see an easy way to do it. If you decide to change everything back to "\includegraphics" it will break the reproducibility and also be a lot of extra work. Wouldn't it be easier to just tag each figure by hand in Adobe acrobat once the doc is built?

**Comment by grinnellm** [comment]
Thanks Chris -- that does sound like a better option, especially if it's possible using RMarkdown. If it's not too hard, I'd like to switch to RMarkdown for the next herring document..

**Comment by cgrandin** [comment]
That's the plan, to get us all on board with RMarkdown. I started it already but it going to take awhile

**Comment by cgrandin** [comment]
You're right, if you forget to delete.rdata.files() and build() then the old model outputs will be used. This was done because it takes a long time to create those individual rdata files and they don't change that often once we've decided on models.

The way I debug all my code is paste the line that I have in a comment at the beginning of all.R, then you can debug any code in the document as if you are in the document. It's as if you are inside the document environment once you've run those few commands. 

I've since (in PCod) incorporated the build() directly into the document so that happens if the files don't exist.

Sean does things yet another way, RStudio is set up to deal with RMarkdown and so you can debug the code chunks directly from the document code. Anyway, I will work on getting everything ported to RMarkdown for the next cycle.

**Comment by andrew-edwards** [comment]
Great that it sounds like you've figured this out. I wasn't quite sure how it would work with knitr. 

How about maybe just manually putting the \pdftooltips into the FINAL .tex version of the document? The alt text only needs to be done once for the very final version. Doesn't strictly need to be reproducible. A bit tedious to do manually at the end (but quicker than by hand in Adobe).  So run the .pdf by CSAP to say is everything fine except for alt text, then we add the alt text in at the end.

**Comment by grinnellm** [comment]
Good suggestion, thanks Andy. I hadn't thought of editing the *.tex file.
