### ISSUE TITLE
Unable to calculate same posterior recruitment estimates as in tables

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/HerringAssess#42]
I'm trying to calculate posterior recruitment estimates, but my values are slightly different from the tables in the SR (below for HG; the tables are created if you uncomment lines 136 and 137 in "sci-resp.rnw"):

![image](https://user-images.githubusercontent.com/25674027/51926506-4b840f80-23a6-11e9-8e79-5dc9a07541bf.png)

I'm using 
`Lower <- apply( X=dat, MARGIN=2, FUN=function(y) quantile(x=y, probs=0.05) )`
where `Lower` is the 5th percentile, and `dat` is "iscam_rt_mcmc.csv." What am I missing?

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Year </th>
   <th style="text-align:left;"> Lower </th>
   <th style="text-align:left;"> Median </th>
   <th style="text-align:left;"> Upper </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 2007 </td>
   <td style="text-align:left;"> 44.846 </td>
   <td style="text-align:left;"> 68.027 </td>
   <td style="text-align:left;"> 101.547 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2008 </td>
   <td style="text-align:left;"> 213.608 </td>
   <td style="text-align:left;"> 306.291 </td>
   <td style="text-align:left;"> 436.442 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2009 </td>
   <td style="text-align:left;"> 37.130 </td>
   <td style="text-align:left;"> 56.326 </td>
   <td style="text-align:left;"> 86.743 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2010 </td>
   <td style="text-align:left;"> 151.896 </td>
   <td style="text-align:left;"> 219.654 </td>
   <td style="text-align:left;"> 310.963 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2011 </td>
   <td style="text-align:left;"> 98.962 </td>
   <td style="text-align:left;"> 145.956 </td>
   <td style="text-align:left;"> 213.228 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2012 </td>
   <td style="text-align:left;"> 414.913 </td>
   <td style="text-align:left;"> 581.740 </td>
   <td style="text-align:left;"> 826.076 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2013 </td>
   <td style="text-align:left;"> 54.027 </td>
   <td style="text-align:left;"> 80.230 </td>
   <td style="text-align:left;"> 118.999 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2014 </td>
   <td style="text-align:left;"> 89.286 </td>
   <td style="text-align:left;"> 131.632 </td>
   <td style="text-align:left;"> 194.308 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2015 </td>
   <td style="text-align:left;"> 63.245 </td>
   <td style="text-align:left;"> 95.653 </td>
   <td style="text-align:left;"> 143.135 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2016 </td>
   <td style="text-align:left;"> 141.939 </td>
   <td style="text-align:left;"> 220.358 </td>
   <td style="text-align:left;"> 341.466 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2017 </td>
   <td style="text-align:left;"> 142.271 </td>
   <td style="text-align:left;"> 231.790 </td>
   <td style="text-align:left;"> 373.112 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2018 </td>
   <td style="text-align:left;"> 31.730 </td>
   <td style="text-align:left;"> 59.477 </td>
   <td style="text-align:left;"> 108.909 </td>
  </tr>
</tbody>
</table>

**Comment by jaclyncleary** [comment]
Note: MPD values match between the summary tables and the mcmc outputs.

**Comment by grinnellm** [comment]
Sorry @cgrandin , I hear you're still swamped with Hake. @jaclyncleary had a thought that maybe some values in the recruitment vector are inadvertently recycled because the recruitment age-2 vector is shorter than most other vectors (recruitment starts in 1953, instead of 1951 like most other vectors).

**Comment by cgrandin** [comment]
It's ok. I'm waiting for a routine to finish...
 If you look at calc.mcmc() function you'll see that the data are burned in with 1000. So try removing the first thousand and you should get the same numbers

**Comment by grinnellm** [comment]
Yup, that works to remove the first 1000, thanks!

**Comment by grinnellm** [comment]
Just want to clarify that our text in the ResDoc regarding this correct: "posterior samples were drawn systematically every 1,000 iterations from a chain of length 5 million, resulting in 5,000 posterior samples." Instead, should we say that it resulted in 4,000 posterior samples (since we discard the first 1,000)?

**Comment by cgrandin** [comment]
Yes, and you should mention that the first 1000 samples were discarded as burn-in for the MCMC chain
