### ISSUE TITLE
model diagnostic Figures for SR "Appendix"

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#7]
pls add from 2017 REs Doc to SR "Appendix"
Fig 20
Fig 21-30 -- AM2 only
Fig 31-40 -- AM2 only
Fig 41-50 -- AM2 only
Fig 51-60 -- AM2 only

**Comment by grinnellm** [comment]
Done. All except Fig 20 were added by @cgrandin -- thanks!
