### ISSUE TITLE
storyboard plot edits

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#8]
few edits for the storyboard:
1) remove LRP estimates from panel (a)
2) make circles a touch smaller for (f) - this will reduce overlap when I blow the fig up on my screen
3) add 3-year running average trend line through the median log rec_devs estimates in (e). Use red. See inserted fig.
4) reduce white space by:
i) chaneging yaxis on (c) to x1000 million
ii) remove xaxis "Year" label from (d)
iii) remove secondary xaxis from (f) - remove the depletion values
iv) shrink white space between yaxis and ylab (all)

![image](https://user-images.githubusercontent.com/2219398/46305685-fb677e80-c566-11e8-9ce5-d8b2f34a964d.png)

**Comment by grinnellm** [comment]
Done.
