### ISSUE TITLE
Table 7-11 (eg, prd.ref.points.table)

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/HerringAssess#9]
I need four values add to Tables 7-11:

SB2018/ 0.3SB0
SB2019/ 0.3SB0
p(SB2018 < 0.3SB0)
p(SB2019 < 0.3SB0)

pls and thx

**Comment by cgrandin** [comment]
I will work on this

**Comment by cgrandin** [comment]
Done. You need to:

source("R/all.R");delete.rdata.files()

before rebuilding the document for the tables to be changed!
